name: zap dast scan

on:
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://34.105.229.136/'          
